[refactor] LoginService 리팩토링
Pin-Tree/backend pull request #31
Opened 2021-09-03 09:47 UTC by pbg0205

### 연습삼아 해본 리팩토링 코드

이번에 작업한거는 이렇게 작업해보자고 PR 날린거는 아니구

요렇게 한번 중복되는 코드 리팩토링 연습해보려고 변경해본 코드인데 

두 사람 코드 리뷰 한번 받아보고 싶어서 PR 날려~~

그냥 보고 간단한 코멘트만 부탁해~~

2021-09-22 06:10 UTC, sanhee approved these changes
리뷰가 너~~~~~~~~무 늦어서 죄송합니다.
이제 방황 멈추고 다시 열심히 하겠습니다!!

enum과 제네릭으로 중복 코드 제거하신 거 깔끔하고 좋네요!
저는 이렇게 가져가도 좋다고 생각합니다.

2021-09-22 07:14 UTC, jihye-woo requested changes
enum으로 서비스 빈의 이름을 안전하게 들고올 수 있고, Controller에서 중복된 메소드를 제거할 수 있어서 코드가 더 깔끔해졌네요!ㅎㅎ 기분이 좋습니다

그리고 한 가지 질문 사항이 있어서 코멘트 따로 드렸는데 확인 부탁드립니다!! 감사합니다😃 수고하셨습니다

2021-09-22 07:14 UTC, jihye-woo commented on pintree/src/main/java/com/trio/pintree/login/service/LoginService.java
>          MemberResponseDto memberResponse = MemberResponseDto.fromEntity(member);
### 궁금한게 있습니다!! 🙋‍♀️

`getUserProfile()`의 실제 리턴 타입은 `UserProfile`
`getJwtResponse()`의 실제 리턴 타입은 `JwtResponse` 인데 

구체적인 리턴타입을 명시해주지 않고 둘 다 `<T extends OauthService>`로 설정해주신 이유가 무엇인가요??

`<T extends OauthService>`가 OauthService를 상속받는 모든 클래스를 리턴타입으로 허용한다는 의미로 알고있는데, 그렇게 되면 getUserProfile()에서 UserProfile 타입이 아니라 조건에 만족하는 다른 타입을 리턴해도 컴파일 에러가 발생하지 않게 될 것 같아서요!!

제가 코드의 의도를 제대로 파악하지 못했다면..!! 조금만 더 설명해주시면 감사드리겠습니다!🙇‍♀️

2021-09-22 07:36 UTC, pbg0205 commented on pintree/src/main/java/com/trio/pintree/login/service/LoginService.java
>          MemberResponseDto memberResponse = MemberResponseDto.fromEntity(member);
코드의 의도는 generic을 사용함으로써 `대입 가능한 파라미터의 범위`를 지정하고 싶었습니다. 제네릭은 컴파일 타임에서 형변환을 확인하고 적합하지 않을 경우에 에러를 반환하고 싶었습니다. 제네릭을 실제 적용한 경험이 없어 우디의 의중을 정확히 파악하지 못했네요ㅠ 혹시 괜찮으시면 해당 원인을 야기할 수 있는 예시에 대해 부탁드려도 괜찮을까요??

2021-09-22 07:43 UTC, jihye-woo commented on pintree/src/main/java/com/trio/pintree/login/service/LoginService.java
>          MemberResponseDto memberResponse = MemberResponseDto.fromEntity(member);
아아 제가 제네릭에 대해서 제대로 알지못했던 것 같아요!!
`<T extends OauthService>` 를 리턴 타입으로 순간 착각했습니다
죄송해요 이제야 코드를 제대로 이해했습니다!👍👍

2021-09-22 07:46 UTC, jihye-woo approved these changes

2021-09-23 03:53 UTC, pbg0205 commented
이건 연습삼아 해본 코드라서 `Merge`하지 않겠습니다!

2021-09-23 03:53 UTC, closed without merging